#!/usr/bin/env bash

set -euo pipefail

dist() {
  local forks fork branch
  forks=$(git remote | grep fork- | awk '{print $1}' | sort | uniq)
  for fork in ${forks}; do
    branch=${fork/fork-/}
    echo git checkout "${branch}"
    echo git rebase main
    echo git push --force-with-lease "${fork}" main
  done
}

"${@}"
